let i18n = {
    'chinese': {}
};

i18n.chinese = {

    // all buildings
        'market': '市场',
        'bar': '酒吧',
        'dry dock': '造船厂',
        'harbor': '港口',
        'inn': '旅馆',
        'palace': '皇宫',
        'job house': '工会',
        'misc': '其它',
        'bank': '银行',
        'item shop': '物品店',
        'church': '教堂',
        'fortune house': '占卜屋',

    // ships
    'fleet info': '舰队情况',
        'Fleet Speed': '舰队航速',
        'Flag': '国籍',
            // nations
            'England': '英格兰',
            'Holland': '荷兰',
            'Portugal': '葡萄牙',
            'Spain': '西班牙',
            'Italy': '意大利',
            'Turkey': '土耳其',

            // ships
            'Atakabune' : '安宅船',
            'Balsa' : '轻木帆船',
            'Brigantine' : '多桅小型帆船',
            'Buss' : '巴斯渔船',
            'Caravela Latina' : '拉丁帆卡拉维尔帆船',
            'Caravela Redonda' : '方形帆卡拉维尔帆船',
            'Carrack' : '武装帆船',
            'Dhow' : '轻型阿拉伯帆船',
            'Flemish Galleon' : '佛兰德帆船',
            'Galleon' : '西班牙大帆船',
            'Hansa Cog' : '汉萨柯克帆船',
            'Junk' : '中式帆船',
            'Kansen' : '日式帆船',
            'La Reale' : '法兰德斯排桨帆船',
            'Light Galley' : '轻型排桨帆船',
            'Nao' : '中型帆船',
            'Pinnace' : '北海多桅帆船',
            'Sloop' : '单桅纵帆船',
            'Talette' : '单桅帆船',
            'Venetian Galeass' : '威尼斯炮舰',
            'Xebec' : '多桅阿拉伯帆船',
            'Barge' : '三桅大型帆船',
            'Full Rigged Ship' : '战列舰',
            'Frigate' : '护卫舰',
            'Tekkousen' : '铁甲船',

        // right hud
            // in port
            'Economy': '商业指数',
            'Industry': '工业指数',

                // regions
                'Iberia': '伊比利亚',
                'Northern Europe': '北欧',
                'The Mediterranean': '地中海',
                'North Africa': '北非',
                'Ottoman Empire': '奥斯曼帝国',
                'West Africa': '西非',
                'Central America': '中美洲',
                'South America': '南美洲',
                'East Africa': '东非',
                'Middle East': '中东',
                'India': '印度',
                'Southeast Asia': '东南亚',
                'Far East': '远东',

    // ports
    'Lisbon' : '里斯本',
    'Seville' : '塞维利亚',
    'Istanbul' : '伊斯坦布尔',
    'Barcelona' : '巴塞罗那',
    'Algiers' : '阿尔及尔',
    'Tunis' : '突尼斯',
    'Valencia' : '瓦伦西亚',
    'Marseille' : '马赛',
    'Genoa' : '热那亚',
    'Pisa' : '比萨',
    'Naples' : '那不勒斯',
    'Syracuse' : '锡拉库萨',
    'Palma' : '帕尔马',
    'Venice' : '威尼斯',
    'Ragusa' : '拉古萨',
    'Candia' : '干地亚',
    'Athens' : '雅典',
    'Salonika' : '萨洛尼卡',
    'Alexandria' : '亚历山大',
    'Jaffa' : '雅法',
    'Beirut' : '贝鲁特',
    'Nicosia' : '尼科西亚',
    'Tripoli' : '的黎波里',
    'Kaffa' : '卡法',
    'Azov' : '亚速尔',
    'Trebizond' : '特雷比松',
    'Ceuta' : '休达',
    'Bordeaux' : '波尔多',
    'Nantes' : '南特',
    'London' : '伦敦',
    'Bristol' : '布里斯托',
    'Dublin' : '都柏林',
    'Antwerp' : '安特卫普',
    'Amsterdam' : '阿姆斯特丹',
    'Copenhagen' : '哥本哈根',
    'Hamburg' : '汉堡',
    'Oslo' : '奥斯陆',
    'Stockholm' : '斯德哥尔摩',
    'Lubeck' : '吕卑克',
    'Danzig' : '但泽',
    'Riga' : '里加',
    'Bergen' : '卑尔根',
    'Caracas' : '加拉加斯',
    'Cartegena' : '卡特基那',
    'Havana' : '哈瓦那',
    'Margarita' : '玛格丽塔',
    'Panama' : '巴拿马',
    'Porto Velho' : '波多韦柳',
    'Santo Domingo' : '圣多明哥',
    'Veracruz' : '维拉克鲁斯',
    'Jamaica' : '牙买加',
    'Guatemala' : '危地马拉',
    'Pernambuco' : '伯南布哥',
    'Rio de Janeiro' : '里约热内卢',
    'Maracaibo' : '马拉开波',
    'Santiago' : '圣地亚哥',
    'Cayenne' : '卡宴',
    'Madeira' : '马德拉',
    'Santa Cruz' : '圣克鲁斯',
    'San Jorge' : '圣乔治',
    'Bissau' : '比绍',
    'Luanda' : '罗安达',
    'Argin' : '阿尔金',
    'Bathurst' : '巴瑟斯特',
    'Timbuktu' : '廷巴克图',
    'Abidjan' : '阿比让',
    'Sofala' : '索法拉',
    'Malindi' : '马林迪',
    'Mogadishu' : '摩加迪沙',
    'Mombasa' : '蒙巴萨',
    'Mozambique' : '莫桑比克',
    'Quelimane' : '克利马内',
    'Aden' : '亚丁',
    'Hormuz' : '霍尔木兹',
    'Massawa' : '马萨瓦',
    'Cairo' : '开罗',
    'Basra' : '巴士拉',
    'Mecca' : '麦加',
    'Quatar' : '卡塔尔',
    'Shiraz' : '设拉子',
    'Muscat' : '马斯喀特',
    'Diu' : '迪乌',
    'Cochin' : '科钦',
    'Ceylon' : '锡兰',
    'Amboa' : '安博亚',
    'Goa' : '果阿',
    'Malacca' : '马六甲',
    'Ternate' : '特内',
    'Banda' : '班达',
    'Dili' : '迪力',
    'Pasei' : '帕塞',
    'Sunda' : '翼它',
    'Calicut' : '卡利卡特',
    'Bankao' : '班考',
    'Zeiton' : '泉州',
    'Macao' : '澳门',
    'Hanoi' : '河内',
    'Changan' : '长安',
    'Sakai' : '坂井',
    'Nagasaki' : '长崎',
    'Hekla' : '赫克拉',
    'Narvik' : '纳尔维克',
    'Cape Town' : '开普敦',
    'Belgrade' : '贝尔格莱德',
    'Tamatave' : '塔马塔夫',
    'Dikson' : '迪克森',
    'Lushun' : '旅顺',
    'Leveque' : '列夫奎',
    'Mindanao' : '棉兰老',
    'Tiksi' : '提克西',
    'Ezo' : '埃佐',
    'Geelong' : '吉隆',
    'Guam' : '关岛',
    'Moresby' : '莫尔斯比',
    'Korf' : '科尔夫',
    'Wanganui' : '旺加努伊',
    'Suva' : '苏瓦',
    'Nome' : '诺姆',
    'Naalehu' : '纳阿勒胡',
    'Tahiti' : '塔希提',
    'Juneau' : '朱诺',
    'Coppermine' : '科珀曼',
    'Santa Barbara' : '圣巴巴拉',
    'Churchill' : '丘吉尔',
    'Callao' : '卡劳',
    'Valparaiso' : '瓦尔帕莱索',
    'Mollendo' : '莫勒多',
    'Cape Cod' : '鳕鱼角',
    'Montevideo' : '蒙拖维迪亚',
    'Forel' : '法雷尔',

    // goods
    'Food': '食物',
    'Water': '水',
    'Clove' : '丁香',
    'Cinnamon' : '肉桂',
    'Pepper' : '胡椒',
    'Nutmeg' : '肉豆蔻',
    'Pimento' : '玉桂子',
    'Ginger' : '姜',
    'Tobacco' : '烟草',
    'Tea' : '茶',
    'Coffee' : '咖啡',
    'Cacao' : '可可',
    'Sugar' : '糖',
    'Cheese' : '奶酪',
    'Fish' : '鱼',
    'Grain' : '谷物',
    'Olive Oil' : '橄榄油',
    'Wine' : '葡萄酒',
    'Rock Salt' : '岩盐',
    'Silk' : '丝绸',
    'Cotton' : '棉花',
    'Wool' : '羊毛',
    'Flax' : '亚麻',
    'Cotton Cloth' : '棉布',
    'Silk Cloth' : '丝绸布',
    'Wool Cloth' : '羊毛布',
    'Velvet' : '天鹅绒',
    'Linen Cloth' : '亚麻布',
    'Coral' : '珊瑚',
    'Amber' : '琥珀',
    'Ivory' : '象牙',
    'Pearl' : '珍珠',
    'Tortoise Shell' : '玳瑁甲',
    'Gold' : '黄金',
    'Silver' : '白银',
    'Copper Ore' : '铜矿石',
    'Tin Ore' : '锡矿石',
    'Iron Ore' : '铁矿石',
    'Art' : '美术品',
    'Carpet' : '地毯',
    'Musk' : '麝香',
    'Perfume' : '香水',
    'Glass Beads' : '玻璃珠',
    'Dye' : '染料',
    'Porcelain' : '陶瓷器皿',
    'Glassware' : '玻璃器皿',
    'Arms' : '武器',
    'Wood' : '木材',

    // villages
    'Kiwi' :  '几维鸟',
    'Koala' :  '考拉',
    'Ayers Rock' :  '艾尔斯岩',
    'Tasmanian Devil' :  '塔斯马尼亚小人',
    'Frilled Lizard' :  '褶边蜥蜴',
    'Kangaroo' :  '袋鼠',
    'Popol Vuh' :  '波波乌',
    'Jade Mask' :  '玉制面具',
    'Guatavita Lake' :  '瓜塔维塔湖',
    'Monument of the Sun' :  '太阳纪念碑',
    'Crystal Skull' :  '水晶骷髅',
    'Mexican Beaded Lizard' :  '墨西哥蜥蜴',
    'Stone Face' :  '石脸',
    'Mural of Marnalico' :  '马纳利科壁画',
    'Stone Ball' :  '石球',
    'Mandrill' :  '山楂',
    'Panda' :  '熊猫',
    'Great Wall' :  '长城',
    'Qian Ling' :  '乾陵',
    'Hedgehog' :  '刺猬',
    'Namahage' :  '鬼怪',
    'Toro Ruins' :  '托罗遗址',
    'Plant Worm' :  '虫草',
    'King Cobra' :  '眼镜王蛇',
    'Mohenio-Daro' :  '摩亨佐-达罗',
    'Inle Lake' :  '茵莱湖',
    'Chameleon' :  '变色龙',
    'Dodo' :  '渡渡鸟',
    'Burning Water' :  '石油',
    'Papyrus' :  '纸草',
    'Rosetta Stone' :  '罗塞塔石',
    'Crocodile' :  '鳄鱼',
    'Pteranodon' :  '翼龙',
    'Nubia Pyramid' :  '努比亚金字塔',
    'Tessisat Falls' :  '泰西萨特瀑布',
    'Baobab' :  '猴面包树',
    'Khufu Pyramid' :  '胡夫金字塔',
    'Victoria Falls' :  '维多利亚瀑布',
    'Prairie Dog' :  '草原犬鼠',
    'Bison' :  '野牛',
    'Passenger Pigeon' :  '信鸽',
    'Totem Pole' :  '图腾柱',
    'Niagara Falls' :  '尼亚加拉瀑布',
    "Venus' Flytrap" :  '捕蝇草',
    'Great Auk' :  '大海雀',
    'Mammoth' :  '猛犸',
    'Saber-toothed Tiger' :  '剑齿虎',
    'Stonehenge' :  '巨石阵',
    'Blue Whale' :  '蓝鲸',
    "Stellar's Sea Cow" :  '海牛',
    'Big Zimbabwe' :  '大津巴布韦',
    "Diaz's Monument" :  "迪亚士纪念碑",
    'Vampire Bat' :  "吸血蝙蝠",
    'Terracotta Figure' :  "陶俑",
    'Lake Titicaca' :  "提提卡卡湖",
    'Temple of the Sun' :  '太阳神庙',
    'Giant Ground Sloth' :  '地懒',
    'Clay Monster' :  '粘土怪',
    'Anteater' :  "食蚁兽",
    'Leon Penguin' :  "利昂企鹅",
    'Archaeopteryx' :  "始祖鸟",
    'Gold Frog' :  "黄金蛙",
    'Matamata' :  "马塔玛塔",
    'Pororoca' :  "波罗卡",
    'Tarantula' :  "塔兰托毒蛛",
    'Anaconda' :  '水蟒',
    'Amazon Water Lily' :  "亚马逊水百合",
    'Piranha' :  '食人鱼',
    'Iguana' :  '鬣蜥',
    'Toucan' :  '巨嘴鸟',
    'Cactus' :  '仙人掌',
    'Pitcher Plant' :  '猪笼草',
    'Stone Buddha' :  '石佛',
    'Komodo Dragon' :  '科莫多龙',
    'Borobudur' :  '婆罗浮屠',
    'Python' :  '蟒蛇',
    'Greater Bird of Paradise' :  '天堂鸟',
    'Hornbill' :  '犀鸟',
    'Angkor Wat' :  '吴哥窟',
    "Ayutthaya's Buddha" :  '大城府大佛',
    'Durian' :  '榴莲',
    'Tree Snake' :  '树蛇',
    'Kalavinka' :  '卡拉文卡',
    'Moai' :  '复活节岛',
    'Nasiped' :  '怪怪鼠',
    'Giant Tortoise' :  '巨龟',
    'Indo-Pacific Cowrie' :  '印太海牛',
    'Moa' :  '恐鸟',
    'Fruit Bat' :  "果蝠",
    'Armadillo' :  '犰狳',
    "Diogo's Monument" :  '迪亚哥纪念碑',
    'Moquele Mubembe' :  '曼比龙',
    'Quagga' :  "伯切尔氏斑马",
    'Ant Hill' :  "蚁丘",
    'Clay Mosque' :  '黏土清真寺',
    'Moonbow' :  '月虹',
    'Aurora' :  '极光',

    // items
    'None': '无',
    'Balm' : '圣香油',
    'Lime Juice' : '莱姆果汁',
    'Rat Poison' : '老鼠药',
    'Quadrant' : '四分仪',
    'Sextant' : '六分仪',
    'Theodolite' : '经纬仪',
    'Pocket Watch' : '怀表',
    'Telescope' : '望远镜',
    'Cat' : '猫',
    'Tax Free Permit (E)' : '免税许可证（E）',
    'Tax Free Permit (H)' : '免税许可证（H）',
    'Tax Free Permit (I)' : '免税许可证（I）',
    'Tax Free Permit (P)' : '免税许可证（P）',
    'Tax Free Permit (S)' : '免税许可证（S）',
    'Tax Free Permit (T)' : '免税许可证（T）',
    'Candleholder' : '烛台',
    'Crown of Glory' : '王冠',
    'Garnet Brooch' : '石榴石胸针',
    'Gold Bracelet' : '金手镯',
    'Malachite Box' : '翡翠宝箱',
    'Mermaid Bangle' : '美人鱼手镯',
    'Ruby Scepter' : '红宝石权杖',
    'Aqua Tiara' : '水蓝头饰',
    'China Dress' : '汉服',
    'Circlet' : '圆环',
    'Ermine Coat' : '貂皮大衣',
    'Peacock Fan' : '孔雀扇',
    'Platinum Comb' : '白金梳子',
    'Silk Scarf' : '丝巾',
    'Silk Shawl' : '丝制披肩',
    'Velvet Coat' : '天鹅绒大衣',
    'Leather Armor' : '皮甲',
    'Chain Mail' : '链甲',
    'Half Plate' : '轻型板甲',
    'Plate Mail' : '重型板甲',
    "Errol's Plate" : '埃罗尔板甲',
    'Crusader Armor (*)' : '十字军盔甲（*）',
    'Short Saber' : '短刀',
    'Scimitar' : '弯刀',
    'Japanese Sword' : '日本刀',
    'Saber' : '军刀',
    'Magic Muramasa(*)' : '妖刀村正（*）',
    "Siva's Sword(*)" : '毁灭神剑（*）',
    'Flamberge' : '焰纹剑',
    'Rapier' : '西洋剑',
    'Epee' : '重剑',
    'Estock' : '埃斯托克',
    'Crusader Sword (*)' : '十字军之剑（*）',
    'Cutlass' : '短剑',
    'Broad Sword' : '宽剑',
    'Blue Crescent(*)' : '蓝月（*）',
    'Claymore' : '双刃剑',
    'Golden Dragon(*)' : '金龙（*）',
    'Treasure Box' : '宝箱',
    'Diamond Ring' : '钻戒',

    // mate names
    'John' : '约翰',
    'Tommy Branson' : '汤姆·布兰森',
    'Charlie Stephens' : '查理·斯蒂芬斯',
    'Amy Clement' : '亚美·克莱蒙特',
    'Ambroise Einger' : '安布罗伊斯·艾因格',
    'Amerigo Bassio' : '阿梅里戈·巴希奥',
    'Anthony Morgan' : '安东尼·摩根',
    'Antoine Fitch' : '安东尼·费奇',
    'Antonio Pintado' : '安东尼奥·品塔多',
    'Benito Gomez' : '贝尼托·戈麦斯',
    'Bernando Sanchez' : '伯南多·桑切斯',
    'Carmine Ragussa' : '卡门·拉古萨',
    'Cisco Alvarez' : '思科·阿尔瓦雷斯',
    'Cizzario Fedeliti' : '西扎里奥·费德丽蒂',
    'Dante Peleira' : '但丁·佩莱拉',
    'Diego Fagundes' : '迭戈·法贡德斯',
    'Fernan Pinto' : '费尔南·平托',
    'Fritz Ramsey' : '弗里茨·拉姆齐',
    'Irma Gunter' : '伊尔玛·冈特',
    'Fabian Bernal' : '法比安·贝尔纳',
    'Francis Fielding' : '弗朗西斯·菲尔丁',
    'Raymond Brewster' : '雷蒙德·布鲁斯特',
    'Arthur Oliver' : '亚瑟·奥利弗',
    'Gary Buck' : '加里·巴克',
    'Poppy Chapman' : '波比·查普曼',
    'Peter Hobson' : '彼得·霍布森',
    'Dwight Stephens' : '德怀特·斯蒂芬斯',
    'Donald Russell' : '唐纳德·拉塞尔',
    'Edgar Wheeler' : '埃德加·惠勒',
    'Boris Dutt' : '鲍里斯·杜特',
    'Saxon Wild' : '撒克逊·怀尔德',
    'Ken Harrison' : '肯·哈里森',
    'Erin Howard' : '艾琳·霍华德',
    'Rudolf Flynn' : '鲁道夫·弗林',
    'Tim Hill' : '蒂姆·希尔',
    'Mark Rhys' : '马克·里斯',
    'Paul Lindberg' : '保罗·林德伯格',
    'Al Fasi' : '阿尔·法西',
    'Carl Dupont' : '卡尔·杜邦',
    'Wade Galbraith' : '韦德·加尔布雷斯',
    'Bernard Stevenson' : '伯纳德·史蒂文森',
    'Lawrence Thorndike' : '劳伦斯·桑代克',
    'Abraham Pearson' : '亚伯拉罕·皮尔森',
    'Noah Holt' : '诺亚·霍尔特',
    'Duke Stowe' : '杜克·斯托',
    'Antony Cooper' : '安东尼·库珀',
    'Perry Frederick' : '佩里·弗雷德里克',
    'Kirk Churchill' : '柯克·丘吉尔',
    'York Wagner' : '约克·瓦格纳',
    'Lester Walkley' : '莱斯特·沃克里',

    // maid names
    'Layla' : '莱拉',
    'Melanie' : '梅兰妮',
    'Johanna' : '乔安娜',
    'Tisa' : '蒂莎',
    'Helen' : '海伦',
    'Titis' : '提蒂斯',
    'Leticia' : '莱蒂西亚',
    'Elaine' : '伊莱恩',
    'Jamila' : '贾米拉',
    'Mei-Yi' : '梅伊',
    'Theresa' : '特蕾莎',
    'Aruna' : '阿露纳',
    'Claudia' : '克劳迪娅',
    'Isabella' : '伊莎贝拉',
    'Ladia' : '拉迪亚',
    'Lucia' : '露琪亚',
    'Lillian' : '莉莉安',
    'Rukia' : '鲁奇亚',
    'Mathilda' : '玛蒂尔达',
    'Lupe' : '卢佩',
    'Salma' : '萨尔玛',
    'Onatsu' : '奥纳苏',
    'Natasha' : '娜塔莎',
    'Silvia' : '西尔维娅',
    'Tobia' : '托比亚',
    'Shani' : '沙尼',
    'Viveka' : '维卡',
    'Francesca' : '弗兰西丝卡',

    // items descriptions
    "A perfumed oil believed to calm storms." : '一种被认为是可以用来平息风暴的香油。',
    "A great remedy for scurvy, the disease of poor nutrition that often troubles a crew during long voyages." : '治疗坏血病的良药',
    "A poison to get rid of rats on a ship. Those pesky animals will feast on your precious food if you don't have a way to get rid of them." : '可以干掉船上的老鼠。\n放任它们不管的话，\n你的粮食就要遭殃了。',
    "A low precision instrument use for celestial navigation. It measures longitude and latitude." : '用于测量经纬度的仪器。\n精度比较低。这个价格，\n您还想怎样？',
    "A high precision instrument used for celestial navigation. It measures longitude and latitude." : '用于测量经纬度的仪器。\n精度比较高。',
    "The most precise and reliable instrument used for celestial navigation. It measures longitude and latitude." : '用于测量经纬度的仪器。\n精度非常高。我是最棒的！',
    "A handy portable watch. With it, you'll always know the correct time." : '便捷的怀表。有了它，\n妈妈再也不用担心我的学习。',
    "An optical instrument that will help you find distant objects and ports at sea." : '可以让您看得非常远的\n光学仪器。',
    "Not only does a cat make a nice pet, but it'll keep your ship rat-free!" : '来自168光年外的喵星。\n不仅可撸，还能捕鼠。',
    "A permit issued by England. It gives one tax-exempt status when trading in ports allied with England." : '英国政府发行的许可证。\n在英国的同盟港交易时，\n可以免去税务。',
    "A permit issued by Holland. It gives one tax-exempt status when trading in ports allied with Holland." : '荷兰政府发行的许可证。\n在荷兰的同盟港交易时，\n可以免去税务。',
    "A permit issued by Italy. It gives one tax-exempt status when trading in ports allied with Italy." : '意大利政府发行的许可证。\n在意大利的同盟港交易时，\n可以免去税务。',
    "A permit issued by Portugal. It gives one tax-exempt status when trading in ports allied with Portugal." : '葡萄牙政府发行的许可证。\n在葡萄牙的同盟港交易时，\n可以免去税务。',
    "A permit issued by Spain. It gives one tax-exempt status when trading in ports allied with Spain." : '西班牙政府发行的许可证。\n在西班牙的同盟港交易时，\n可以免去税务。',
    "A permit issued by Turkey. It gives one tax-exempt status when trading in ports allied with Turkey." : '奥斯曼帝国政府发行的许可证。\n在奥斯曼帝国的同盟港交易时，\n可以免去税务。',
    "An antique candleholder made of brass." : '一盏古代的青铜制烛台',
    "A gold crown with delicate decorations." : '装饰细致的金质王冠',
    "A beautifully designed brooch set with beautiful garnets." : '一枚镶嵌着漂亮\n石榴石的胸针',
    "A wide, heavy, solid gold bracelet set with diamonds." : '镶有钻石的宽大金手镯',
    "A small box cut out of malachite stone." : '孔雀石制作的小盒子',
    "A dazzling gold bracelet decorated with beautiful opals." : '闪亮的镶有猫眼石的金手镯',
    "A scepter with a huge ruby size of an egg at the top." : '头部镶有鸡蛋般大小\n红宝石的权杖',
    "An intricately decorated tiara set with small but brilliant aquamarine stones." : '镶有蓝宝石的精致头饰',
    "A beautiful, traditional Chinese dress, made of the finest Chinese silk." : '漂亮的丝质汉服',
    "A beautiful tiara highlighted by a large sapphire in its center." : '中部镶有巨大蓝宝石的头饰',
    "A luxurious coat made from the white winter fur of the rare ermine weasel." : '白鼬皮制成的大衣',
    "A beautiful fan made of long and colorful peacock feathers." : '孔雀羽毛制成的扇子',
    "A fancy comb made of platinum and decorated with rare gems." : '镶有稀有宝石的铂金梳子',
    "A colorful scarf made of fine silk." : '丝绸制成的彩色围巾',
    "A soft shawl made of the best silk from China." : '由中国最好的丝绸制成的披肩',
    "A velvet coat cut in the latest 16th century fashion." : '天鹅绒制成的大衣',
    "A relatively inexpensive armor made of leather that has been hardened with animal grease." : '用动物油硬化过的皮甲。\n比较便宜。',
    "An armor made of thousands of tiny interlinked steel rings. While it allows the wearer ease of movement, it doesn't offer the best protection." : '由上千钢制环链接制成的盔甲。\n它让使用者可以移动自如，\n但是并不提供最好的防护',
    "An armor with sheets of tough, thin steel plates that cover only the upper body. An improvement of plate armor, it's designed for more active naval combats." : '由钢板制成的铠甲，\n只保护上半身。\n专门为海战设计的。',
    "A step up from chain mail armor, this armor is formed by a combination of plate and mail. It offers better protection than Half Plate Armor." : '由钢板和钢环混合制成的铠甲。',
    "Half plate armor made by the famous Copenhagen armorer, Errol. It provides greater protection than plate mail armor." : '由著名的哥本哈根铁匠\n艾洛尔制成的板甲。',
    "Armor that the famous armorer, Montaguinus made-to-order for Affonso, the founding king of Portugal." : '蒙太奇纳斯为葡萄牙开国\n国君阿方索锻造的铠甲',
    "A light, slender sword used by cavalry. It's less effective in an attack than a Saber, but its low price makes it popular." : '骑士用的轻型刺剑。\n便宜的价格使其十分普遍',
    "A curved saber with an outer cutting edge. A great weapon for attacking, it's mainly used by Arabs and Persians." : '阿拉伯和波斯人爱用的弯刀',
    "A very sharp sword made in Japan. It's especially effective for lashing attacks." : '日本制造，非常锋利。适合劈砍。',
    "A curved single-edged cavalry sword that is more effective for lashing than for thrusting." : '有弯曲单刃的骑兵剑。',
    "A treasured sword made in the 15th century by a famous Japanese sword smith, Muramasa." : '村正家族制作的名刀',
    "A legendary sword that's believed to confine the power of Siva, the Hindu god of destruction. A powerful lashing weapon." : '印度传说中蕴含着\n毁灭之神力量的神剑。',
    "A long decorative sword with wavy edges. Its offensive capability is superior to both the Rapier and the Estock." : '有着波浪形刀刃的长剑。',
    "A light, slender, two-edged sword used only for thrusting. It came into use after guns made armor obsolete." : '适合刺击的双刃刺剑。',
    "A light sword with a sharp-pointed blade but no cutting edge, used only for thrusting in dueling. It's not very effective when it comes to attacking." : '没有刀刃，但是剑末锋利的刺剑。',
    "A sword developed to pierce the armor of a mounyed enemy. It has higher attack rate than a rapier." : '被认为是可以刺穿骑兵盔甲的剑。',
    "A special sword with razor-like sharpness made by the renowned swordsmith, Michelangelo." : '米开朗基罗制造的利剑',
    "A heavy, curved sword that historically has been used by sailors." : '历来水手们惯用的重型弯刀',
    "A sword with a wide, straight, single-edged blade. It's especially effective for striking." : '只有一边刀刃的阔剑',
    "A unique Chinese sword with a wide crescent-shaped blade. It's quite good for attacking, especially striking." : '中国制造，剑刃呈现出独特的新月形。',
    "A large two-handed sword from Scotland that may weigh up to 10 pounds. It's quite effective for striking." : '来自苏格兰的双手重剑，\n可能有10磅重。',
    "A unique Chinese sword with wide blade. It's quite effective for striking." : '中国制造的宽刃剑。',
    "A box full of shiny treasures." : '一个装满财宝的箱子',
    "A ring with a large diamond on it." : '一枚镶有巨大钻石的戒指',

    // villages
    "Named for its cry, this is a flightless, nocturnal bird with a small head and a long, slender bill that has nostrils near the tip. It uses its highly developed sense of smell to find its food." : '这是一种不会飞的夜行鸟，\n因其叫声而得名，头部小，\n嘴细长，鼻尖附近有鼻孔。\n它利用高度发达的嗅觉来寻找食物。',
    "A tree-dwelling marsupial mammal that only eats the leaves of the eucalyptus tree. Koala young spend their first 6 months in their mother's pouch, feeding on predigested eucalyptus leaves." : '只吃桉树叶子的树栖有袋哺乳动物。\n考拉幼仔头6个月在母亲的育儿袋里度过，\n以母亲预消化过的桉树叶为食。',
    "A legend says that there is a humongous red monolith in the center of this continent." : '传说在这块大陆的中心\n有一块巨大的红色巨石。',
    "A 30 inch long nocturnal animal that feeds on small animals and carrion. It hides in the cracks of rocks and trees." : '一种30英寸长的夜间活动的动物，\n以小动物和腐肉为食。\n它藏在岩石和树木的裂缝里。',
    "A lizard with a large umbrella-like frill. It rises up and opens the frill to intimidate enemies and runs away only on its rear legs." : '有大伞状褶边的蜥蜴。\n它站起来，打开褶边恐吓敌人，\n只靠后腿逃跑。',
    "Its long fat tail and powerful hind legs help this animal hip-hop along. The newly born infants, still small and pinkish, crawl into a pouch on the mother's belly and remain there during infancy." : '又长又肥的尾巴和有力的后腿\n帮助这种动物跳跃前进。\n刚出生的婴儿，很小，呈粉红色，\n基本上整个婴儿期都待在母亲的育儿袋里。',
    "A manuscript of Mayan legends, describing their philosophy, cosmology, and history." : '印有玛雅传说的手稿，\n描述着他们的哲学、宇宙观和历史。',
    "A mask encrusted with small pieces of jade. Its eye holes give it a somewhat ominous appearance." : '镶有小块玉石的面具。\n它的眼孔让它看起来有点可怕。',
    "A holy place for the Muisca, who throw gold and emeralds into the lake when their new king ascends the throne." : '穆伊斯卡人的圣地，\n当他们的新国王登上王位时，\n穆伊斯卡人将黄金和祖母绿扔进湖中。',
    "A round stone monument symbolizing the sun and the seasons. It represents the Aztec people's concept of the universe." : '象征太阳和季节的圆形石碑。\n它代表了阿兹特克人的宇宙观。',
    "An elaborately sculptured crystal skull used for generations in rituals by tribal leaders." : '一颗精雕细琢的水晶头骨，\n世代用于部落首领的仪式中。',
    "A large lizard with black and yellow bead-like scales. Its secret weapon is its ability to produce poison in its mouth." : '有黑色和黄色珠状鳞片的大型蜥蜴。\n它的秘密武器是能在嘴里产生毒素。',
    "A stone bust excavated from Tenochtitlan." : '从特诺赫蒂兰出土的石像。',
    "A mural of warriors and hunting gods." : '展现着武士和狩猎神的壁画。',
    "A perfectly spherical stone measuring about 6.5 feet in diameter. Its use is unknown." : '一种完美的球形石头，直径约6.5英尺。\n它的用途不详。',
    "Monkey with a colorful face resembling that of a human. It has a beard, purple bottom, and a short tail." : '五颜六色的像人的猴子。\n它有胡子，紫色的屁股和短尾巴。',
    "A large bear-like black and white animal found at high altitudes in mountainous regions. It's friendly and feeds on bamboo." : '一种类似熊的黑白相间的大型动物，\n见于山区的高海拔地区。\n它很友好，以竹子为食。',
    "1500 miles long and averaging 25 feet high, this truly is a great wall. It was constructed over many generations by Chinese rulers as a defense against raids by nomads in the north." : '1500英里长，平均25英尺高，\n这真是一座长城。\n它是中国统治者为抵御北方游牧民族的袭击，\n历经数代，而建造的。',
    "Empress Zetian Wuhou's tomb. A hill with a circumference of 25 miles was turned into this huge tomb where all her treasures are buried." : '女皇帝武则天的墓。\n一座周长25英里的小山\n被改建变成了这个巨大的坟墓，\n她所有的宝藏都埋在这里。',
    "A small mammal with an arsenal of long prickly spines on its back. It rolls itself into a ball when threatened." : '一种小型哺乳动物，\n背部有许多长长的刺。\n当受到威胁时，它会卷成一个球。',
    "Fabled demons that kidnap and devour bad children. The legend is told in a traditional festival where men disguise themselves as demons to scare the town's children." : '传说中绑架并吃掉坏小孩儿的的恶魔。\n这个传说是在一个传统节日里讲的，\n在这个节日里，人们把自己伪装成恶魔\n来吓唬镇上的孩子。',
    "Ruins of farming villages dating from around 300 B.C. The villages had rice fields orderly divided by strong ridges and storehouses with elevated floors." : '大约公元前300年的农业村庄遗址。\n这些村庄有整齐的稻田，\n由坚固的垄和高地板的仓库隔开。',
    "A strange insect which transforms itself into a fungus during the summer. It is highly valued in China as a tonic and an elixir." : '一种奇怪的昆虫，在夏天会变成真菌。\n在中国，它作一种药材很有价值。',
    "The world's largest poisonous snake. When disturbed, it extends its ribs behind its head to form a flaring hood." : '世界上最大的毒蛇。当受到侵扰时，\n它会将肋骨延伸到头部后面，\n形成一个向外扩张的架势。',
    "Ruins of a city dating from the time of the Indus civilization. Built around a dome-shaped Buddhist shrine on a hilltop, this city probably was a commercial center during the Bronze Age." : '印度文明时期的城市废墟。\n这座城市围绕着山顶上一座\n圆顶形的佛教圣地而建，\n在青铜时代可能是一个商业中心。',
    "The people who live here have built their homes and fields on the island that floats on the surface of this lake." : '住在这里的人们在漂浮在湖面上\n的小岛上建起了自己的家园和田地。',
    "Lizard with the amazing ability to change its color to match its surroundings. It's quite adept at capturing insects with its long and sticky tongue." : '蜥蜴有着惊人的改变颜色以适应周围环境的能力。\n它很擅长用又长又粘的舌头捕捉昆虫。',
    "A bird the size of a turkey, with a large hooked bill. Its wings are very small, making it incapable of flight." : '火鸡大小的鸟，有一个大钩状的喙。\n它的翅膀很小，不能飞行。',
    "Strange black liquid that springs out from underground in desert areas. It has a bad smell and burns easily." : '沙漠地区从地下冒出的奇怪的黑色液体。\n它有一股难闻的气味，很容易燃烧。',
    "Tall water plant that was used to make a form of paper in ancient Egypt." : '一种高大的水生植物，\n在古埃及用于造纸。',
    "Black basalt slab bearing the same inscription in three languages- ancient Egyptian hieroglyphics, a simpler ancient Egyptian writing system, and Greek." : '刻有三种语言的黑色玄武岩板：\n古埃及象形文字，\n一种更简单的古埃及书写系统，\n和希腊语。',
    "Fierce amphibious predator armored with hard leather skin, the crocodile sometimes reaches a length of 20 feet. With its powerful jaws, it can rip into livestock animals and even humans with one bite." : '凶猛的两栖捕食者，披着坚硬的皮甲，\n有时长达20英尺。凭借其强大的下颚，\n它可以一口咬死牲畜，甚至人类。',
    "A dark-colored bird whose bat-like wings measure 6 feet across. It's noted for its large beak and sharp teeth." : '一种深色的鸟，蝙蝠状的翅膀宽6英尺。\n它以其大喙和锋利的牙齿而闻名。',
    "Pyramid built by the ancient Cush in northern Africa. Though it's relatively small, with a 30 by 30 foot square base, it has distinctively steep sides." : '古代库什人在北非建造的金字塔。\n它相对较小，有一个30乘30平方英尺的地基，\n有明显的陡峭的一面。',
    "This remote waterfall is 140 feet high and is found near the source of the Blue Nile." : '这个瀑布有140英尺高，\n位于青尼罗河源头附近。',
    "Huge tree with many useful qualities. The bark can be used to fashion rope or cloth, the fruit is edible, and the trunk itself is so large it can be used for storage or even shelter." : '有多种用途的大树。\n树皮可以用来制作绳索或布料，果实可以食用，\n树干本身很大，可以用来储藏甚至遮蔽。',
    "Tomb of the Pharaoh Khufu, a pyramid measuring 481 feet high with a square base 756 feet wide. The four sides face the north, south, east and west." : '法老胡夫的陵墓。高481英尺，\n方形底座宽756英尺。\n四面面朝东、南、西、北。',
    "Believed to be the source of the Nile River. The Zambezi River plunges 400 feet into the lake, forming Victoria Falls." : '被认为是尼罗河的源头。\n赞比西河从400英尺高处注入湖中，\n形成维多利亚瀑布。',
    "Ground-dwelling squirrel-like mammals 11 - 16 inches long. They make their home underground in a complex system of interconnecting burrows with many entrances." : '类似松鼠的地栖哺乳动物，长11-16英寸。\n他们把家建在一个复杂的地下系统中，\n这个系统由许多入口相连的洞穴组成。',
    "A large wild bull that can weigh almost a ton. It is hunted for both food and its hide, which can be used to make leather. Such great numbers roam the plains that it's hard to imagine them ever becoming extinct." : '能重达一吨的大型野牛。\n人们捕猎它既是为了获取食物，\n也是为了获取可以用来制革的兽皮。\n如此大量的动物在平原上游荡，很难想象它们会灭绝。',
    "A beautiful pigeon with slate blue wings and a russet breast. They migrate in large flocks every spring. People say that this species will never become extinct. (Or will it?)" : '一种美丽的鸽子，\n长着蓝灰色的翅膀和赤褐色的胸脯。\n它们每年春天成群结队地迁徙。\n人们说这个物种永远不会灭绝。（真的吗？）',
    "Large wooden pole carved with the designs of animals. It symbolizes the status of the chief, and is sometimes used as a sign of the tribe." : '雕刻有动物图案的大木杆。\n它象征着酋长的地位，\n有时也被用作部落的标志。',
    "A magnificent waterfall, about 158 feet high and 3010 feet wide. Ancient people must have thought that the edge of the earth looks something like this." : '壮观的瀑布，大约158英尺高，3010英尺宽。\n古人认为地球的边缘可能就是这样的。',
    "Insect-eating plant with a jaw-shaped flower that bears sharp spines and secretes a sweet liquid. Once its jaws snap shut they won't reopen until the prey has been digested." : '以昆虫为食的植物，有颚形的花，\n有锋利的刺，能分泌甜味液体。\n一旦它的下颚猛然合上，它们就不会再张开，\n直到猎物被消化掉。',
    "A flightless bird about 30 inches long that makes its home near Greenland. Fishermen hunt this bird for its tasty meat." : '格陵兰岛附近的一种不会飞的鸟，长约30英寸。\n渔夫猎捕这种鸟是为了它的美味。',
    "A legendary giant elephant with a coat of brown wool and long tusks that curve upward." : '一种传说中的巨大大象，\n皮毛为棕色，长牙向上弯曲。',
    "A large carnivorous animal about 6 feet long. Its enormous, blade-like upper teeth extend 7 inches below its lower jaw." : '一种大约6英尺长的大型食肉动物。\n它巨大的，叶片状的上齿延伸到下颚下方7英寸。',
    "Prehistoric monument, consisting of rings of stones, with the outermost ring made up of large stone columns. Believed to have been an astronomical observatory." : '史前纪念碑，由石环组成，\n最外面的环由大石柱组成。\n被认为是一个天文观测站。',
    "The largest animal in the world, sometimes reaching a length of 30 metersand weighing over 150 tons." : '世界上最大的动物，\n有的长达30米，重150多吨。',
    "A large water mammal about 10 feet long. The head resembles a seal and its rear part has a fish-like shape. Locals say its meat is delicious." : '一种大约10英尺长的大型水生哺乳动物。\n头部像海豹，后部呈鱼状。\n当地人说它的肉很好吃。',
    "The name means [large rock house.] It proves that there was once a glorious dynasty in this area." : '这个名字的意思是[大石头屋]，\n它证明了这个地区曾经有一个辉煌的王朝。',
    "Stone monument at the Cape of Good Hope on the southern tip of Africa. It was erected by Bartholomew Diaz and remains a symbol of brave sea adventurers." : '位于非洲南端好望角的石碑。\n它是由巴托洛梅瓦迪亚兹建造的，\n是勇敢的海洋冒险者的象征。',
    "A large bat with a 12 inch wingspan. It uses its sharp teeth to make a shallow wound on its prey, secretes a liquid to prevent the wound from closing, and feeds on its blood." : '翼展12英寸的大蝙蝠。\n它用锋利的牙齿在猎物身上造成浅伤口，\n分泌液体防止伤口闭合，并以血液为食。',
    "This large sculpture represents a legendary hero worshipped by local tribes. Its sculpting technique and intricate design prove that this area has a highly advanced culture." : '这座大型雕塑代表了当地部落崇拜的传奇英雄。\n它的雕刻技术和复杂的设计证明了\n这个地区曾经有高度先进的文化。',
    "The world's highest lake at an altitude of 12,500 feet in the Andes Mountains. The Aztecs believe that a god lives in this lake." : '安第斯山脉海拔12500英尺的世界最高湖泊。\n阿兹特克人相信这个湖里住着一位神明。',
    "A pyramid-shaped shrine in the central Andes, with distinctive frontal stairs climbing 33 feet to the top." : '安第斯山脉中部的金字塔形神庙，\n有独特的正面楼梯，\n通往33英尺高的顶端。',
    "A slow-moving, hairy mammal with sharp claws. Rumor has it this 20 feet tall creature walks upright and feeds on leaves and branches." : '一种行动缓慢、多毛的哺乳动物，有锋利的爪子。\n据传这种20英尺高的生物直立行走，\n以树叶和树枝为食。',
    "A clay figure of a monster with a large head and fangs." : '长着大头和尖牙的泥塑怪物。',
    "A toothless mammal with powerful claws on its front feet and a long tongue that comes in handy for catching ants - the mainstay of its diet. Its long tail accounts for half of its 6 foot length." : '一种无牙的哺乳动物，前脚上有强有力的爪子，\n长舌头方便抓捕蚂蚁——蚂蚁是它的主要食物。\n它的长尾占了它6英尺体长的一半。',
    "A flightless goose-sized bird that uses its wings to swim. Found in large flocks, it was discovered by the Portuguese navigator, Leon Franco." : '一种不会飞的鹅大小的鸟，用翅膀游泳。\n它是由葡萄牙航海家利昂·佛朗哥发现的。',
    "A reptilian bird thought to be an ancestor of today's birds. It had four legs and was unable to fly, but it is believed that this bird-reptile could glide." : '一种很像爬行动物的鸟，被认为是今天鸟类的祖先。\n它有四条腿，不能飞，但可以滑翔。',
    "A primitive vessel used for local inter-tribal trading. This raft has a grass hut mounted on top and uses a square sail." : '用于当地部落间贸易的原始船只。\n这只木筏的顶部有一个草屋，用的是方帆。',
    "A tiny frog with beautiful golden skin that secretes a mysterious poison. Locals believe that this rare frog will guide one to a legendary land of gold." : '一种小青蛙，有美丽的金色皮肤，\n能分泌一种神秘的毒素。当地人相信，\n这种稀有的青蛙会引导人到一个\n传说中的黄金之地。',
    "A spiny turtle with a large diamond-shaped head and an irregular, rugged shell." : '一种多刺的海龟，\n有一个巨大的菱形头部和一个不规则的、粗糙的壳。',
    "An enormous tidal wave that occurs during the new moon in April. Locals say that huge waves may reach over 16 feet high and wash everything away from the shore." : '四月新月期间出现的巨大的潮汐。\n当地人说，巨浪可能高达16英尺以上，\n把所有东西都冲离海岸。',
    "A large hairy poisonous spider that feeds on birds and small animals." : '一种以鸟和小动物为食的\n多毛有毒的大蜘蛛。',
    "A gigantic serpent. Adults may grow 19 feet long and weigh as much as 235 pounds. They are found near the water and crush their victims by constricting them in their coils." : '一种巨大的蛇。成体可能长19英尺，体重高达235磅。\n它们被发现在靠近水面的地方。\n通过缠绕来挤压它们的猎物。',
    "An aquatic plant with giant floating leaves and large flowers. The leaves measure over 6 feet in diameter and are so strong that they can bear the weight of a small child." : '一种水生植物，有巨大的浮叶和大的花。\n叶子直径超过6英尺，非常结实，\n可以承受一个小孩的重量。',
    "The terror of South American rivers. It is not uncommon for these groups of fish to devour people or domesticated animals that try to cross their river." : '南美洲河流里的恐怖存在。\n这些鱼群会吞食试图过河的人或动物。',
    "A large scaly lizard, measuring about 6 feet in length. The row of leathery spines on its back make it look like a fierce dinosaur, but it's actually a gentle creature." : '一种大型带鳞蜥蜴，长约6英尺。\n它背上那排坚韧的刺使它看起来像一只凶猛的恐龙，\n但实际上它是一种温和的生物。',
    "A loud-squawking bird with a huge, brightly colored beak. It feeds chiefly on fruit." : '一种叫声很大的鸟，嘴颜色鲜艳。\n它主要以水果为食。',
    "Spiny, fleshy plant that grows up to 6 feet tall. This unique plant is well-adapted for arid climates." : '多刺的肉质植物，能长到6英尺高。\n这种独特的植物很适合干旱的气候。',
    "A plant that feeds on insects by trapping and digesting them in its pitcher-like leaves." : '一种以昆虫为食的植物，\n通过诱捕昆虫并将其消化\n在其猪笼草状的叶子中。',
    "A huge statue of Buddha carved out of the side of a mountain." : '一座巨大的佛像，被雕刻在一座山的侧面。',
    "A giant slow-moving lizard found only in secluded parts of Indonesia that can grow up to 10 feet long. It uses its long, sharp claws and jagged teeth to attack animals even as large as a small deer." : '一种巨大的缓慢移动的蜥蜴，\n只在印度尼西亚偏远地区发现，\n能长到10英尺长。\n它用长而锋利的爪子和锯齿状\n的牙齿攻击像小鹿一样大动物。',
    "The ruins of a major Buddhist monument. It consists of eight diminishing tiers of terraces connected by stairways. The walls of the corridors are lined with intricately carved relief sculptures." : '一座大型佛教纪念碑的废墟。\n它由八层逐渐减少的梯田组成，\n梯田由楼梯连接。\n走廊的墙壁上排列着雕刻复杂的浮雕。',
    "A giant snake that can grow over 33 feet long in the jungle. After constricting and suffocating an animal, the python swallows its prey whole. " : '在丛林中能长到33英尺长的巨蛇。\n蟒蛇把一只动物勒死后，\n会把猎物整个吞下去。',
    "The male of this beautiful bird has a yellow head, long tail and dark-green throat, but the female has only short feathers and is rather dull in color." : '这种美丽的鸟的雄性有黄色的头、\n长长的尾巴和深绿色的喉咙，\n而雌性只有短羽毛，颜色相当暗淡。',
    "Friendly large-billed bird that makes a hissing sound to intimidate its enemies. It sometimes grows up to 60 inches in height." : '友好的大嘴鸟，发出嘶嘶声以恐吓敌人。\n有的能长到60英寸高。',
    "Ruins of a temple constructed by Khmer during the 12th century. The name means [temple of the capital]." : '高棉人在12世纪建造的一座寺庙的废墟。\n这个名字的意思是[首都的庙宇]。',
    "One of many busts of Buddha found in Siam, which has several temples and statues dedicated to him." : '在暹罗发现的众多佛像半身像中的一尊，\n有多座寺庙和雕像供奉他。',
    "A fruit that is covered with sharp needles. Some say that it is the most delicious of all tropical forest fruits, but it smells so bad that most don't dare taste it." : '覆盖着锋利针叶的水果。\n有人说它是所有热带森林水果中最美味的，\n但它闻起来很奇怪，大多数人都不敢尝。',
    "A slender snake about 3 feet long. The name comes from the fact that it makes its home in trees." : '一条大约3英尺长的细长蛇。\n它的名字来源于它以树为家。',
    "A bird of legend said to have the face of a beautiful girl. Its sweet singing can make people forget everything, even their own names." : '传说中长有一张漂亮女孩的脸的鸟。\n它甜美的歌声能让人忘记一切，\n甚至自己的名字。',
    "Giant stone statues ranging from 15 to 60 feet high. They're carved with large faces, long ears and short bodies." : '巨大的石像高达15到60英尺。\n他们的脸很大，耳朵很长，身体很短。',
    "A creature rumored to resemble a mouse that walks upside down using its highly developed nose. This odd creature is probably fantastical." : '传闻中的一种类似老鼠的生物，\n它用高度发达的鼻子倒立行走。\n这种奇怪的生物可能并不存在。',
    "A large, slow-moving tortoise that can weigh as much as 500 pounds. Its domed shell sometimes grows as long as three feet and serves as protection for its elephant-like skin." : '一种行动缓慢的大乌龟，\n体重可达500磅。\n它的圆顶壳有时能长到三英尺长，\n可以保护它像大象一样的皮肤。',
    "A rare snail with a beautiful shell that lives deep in the sea. Its shell is used as an amulet by tribal leaders and shamans in the area." : '一种珍稀的蜗牛，有美丽的壳，\n生活在海洋深处。\n它的贝壳被当地的部落首领和萨满\n用作护身符。',
    "An ostrich-like bird incapable of flight, measuring over 10 feet in height. Its massive and well-developed hind legs help it run very fast." : '一种像鸵鸟一样不能飞行的鸟，\n身高超过10英尺。\n它庞大而发达的后腿帮助它跑得很快。',
    "Just as the name suggests, this bat lives off of fruit. It is a very rare delicacy at tables throughout the area." : '顾名思义，这种蝙蝠以水果为生。\n在这个地区的餐桌上，\n这是一道非常罕见的佳肴。',
    "Animal with bony plates on its back. When threatened, it curls up to cover its soft unprotected abdomen." : '背上有骨甲的动物。当受到威胁时，\n它会蜷缩起来，遮住它柔软又没有保护的腹部。',
    "A tall stone monument with inscriptions in Latin, Portuguese, and Arabic. Erected when Diogo Cam discovered the Congo." : '一座高大的石碑，上面有拉丁语、葡萄牙语和阿拉伯语的铭文。\n是迪亚戈·卡姆发现刚果时建立的。',
    "The locals of Lake Tele have claimed to have seen this dinosaur from time to time. It's believed to be herbivorous and about 15 feet long." : '特拉湖的当地人声称不时看到这种恐龙。\n据信它是食草的，大约15英尺长。',
    "A horse-like creature related to the zebra, but with no stripes on its hind portion. It takes its name from the sound it makes, {Kwahaha.}" : '一种类似马的动物，与斑马有亲缘关系，\n但后肢没有条纹。\n它的名字来源于它发出的声音{Kwahaha.}',
    "These small ant castles, in their various shapes, often surpass the architectural feats of man." : '这些形状各异的蚂蚁城堡，\n据说堪比人类的建筑成就。',
    "Supposedly, the ruins of a golden city in the Sahara. Time has taken its toll, but the work of conscientious desert dwellers have helped preserve the ancient structure." : '据推测，这是撒哈拉沙漠中一座黄金城市的废墟。\n时间使其风化，\n但尽职尽责的沙漠居民们一直在保护这座古老的建筑。',
    "A rainbow that shines gold and white in the dark night. Legend says that this beautiful, mysterious vision brings good luck to those who see it." : '一道在黑夜中闪耀着金色和白色的彩虹。\n传说这美丽而神秘的景象给看到它的人带来好运。',
    "A luminous atmospheric phenomenon seen in the night sky. Its awesome curtain-like display is constantly changing. While it's something special to see, the magnetic storms that occur with it can disturb your compass." : '夜空中出现的明亮的大气现象。\n它令人敬畏的帘幕不断地变化。\n它虽然好看，但随之而来的磁暴会干扰你的指南针。'
}